#!/usr/bin/env python3
import sys
import threading
import time
import socket

datalock = threading.Lock()
writeevent = threading.Event()

class handle_client(threading.Thread):
	def __init__(self,socket):
		threading.Thread.__init__(self)
		self.socket = socket
	
	def run(self):
		while True:
			writeevent.wait()
			with datalock:
				writeevent.clear()
				self.ser.write(data)

class socketkontrolle(threading.Thread):
	def tumaclient(self, client):
		pass

	def run(self):
		servsocket = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
		servsocket.bind("/tmp/serversocket")
		servsocket.listen(5)
		while True:
			(client,a) = socket.accept()
			tumaclient(client)


while True:
	time.sleep(1)
	print(threading.active_count())
